# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TaipeiPOI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  project './TaipeiPOI.xcodeproj'
  
  use_frameworks!
  pod 'SVProgressHUD'
  pod 'JSONModel'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'LOAlertController'
  # Pods for TaipeiPOI

  target 'TaipeiPOITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TaipeiPOIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
